name: Testing and Deploying Package

# Specifying when should the workflow run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:

jobs:

  build:
  
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
    
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install and Upgrade pip, install other dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install setuptools wheel twine pytest
          pip install -r requirements.txt
          python3 setup.py install
          
      - name: Test with pytest
        run: |
          cd tests
          pytest -q test_msds.py
          cd ..
      
      - name: Build and Uplaod to TestPyPI
        run: |
          python3 setup.py sdist bdist_wheel
          python3 -m twine upload -r testpypi dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: $ {{ secrets.TWINE_PASSWORD }}
        
        
        
        
        
        
        
        




