name: Testing and Deploying Package

# Specifying when should the workflow run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
  
  steps:
    - uses: actions/checkout#v2
    
    #run a single shell command line
    - name: Running a one-line script
      run: echo Hello, world!
 
